
set(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR PIC_8)

set(XC8_PATH "C:/Program Files/Microchip/xc8/v3.10/bin")

set(CMAKE_C_COMPILER "${XC8_PATH}/xc8-cc.exe")
set(CMAKE_ASM_COMPILER "${XC8_PATH}/xc8-cc.exe")
set(CMAKE_OBJCOPY "${XC8_PATH}/avr-objcopy.exe")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wpedantic")
set(CMAKE_C_FLAGS_DEBUG "-g")
set(CMAKE_C_FLAGS_RELEASE "-O3")

set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)